spring.application.name=lab01-redis-caching

spring.datasource.url=jdbc:postgresql://localhost:5432/lab01
spring.datasource.username=lab01
spring.datasource.password=lab01
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.data.redis.host=localhost
spring.data.redis.port=6379
