services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  app-1:
    build: .
    environment:
      SERVER_PORT: 8081
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
    ports:
      - "8081:8081"
    depends_on:
      - redis

  app-2:
    build: .
    environment:
      SERVER_PORT: 8082
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
    ports:
      - "8082:8082"
    depends_on:
      - redis
